# workflow which lints and checks the code on every push and pull request
name: Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: checkout
        uses: actions/checkout@v4

      # https://github.com/actions/setup-python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies

      - name: Install Deps
        run: pip install -r requirements.txt -r requirements.dev.txt

      # https://github.com/pre-commit/action
      - name: run pre-commit
        uses: pre-commit/action@v3.0.0
        env:
          SKIP: no-commit-to-branch
